services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: photo-enhancer-api
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
      - ./models:/app/models
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  # Production service
  api-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: photo-enhancer-api-prod
    volumes:
      - ./uploads:/app/uploads
      - ./models:/app/models
    ports:
      - "8001:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4
    restart: unless-stopped
